

#mybatis 配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

# log配置
logging:
  level:
    com.chf: DEBUG
  file: ./log/springbootlog.log
  root: INFO

